// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSE5yWof7P9p9r46dh3hMVj634cnRKthQ',
    appId: '1:745052584213:web:c437388590ef7517fa111c',
    messagingSenderId: '745052584213',
    projectId: 'hungergo-4f4de',
    authDomain: 'hungergo-4f4de.firebaseapp.com',
    storageBucket: 'hungergo-4f4de.firebasestorage.app',
    measurementId: 'G-9BG7R3DHNM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKMObUXNDPa9Hp6mcGt65BIKTs163UiRw',
    appId: '1:745052584213:android:4eff9e5868961425fa111c',
    messagingSenderId: '745052584213',
    projectId: 'hungergo-4f4de',
    storageBucket: 'hungergo-4f4de.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKHx1iv2FV7DxHbS7NwyVeQ-PfWjI16tM',
    appId: '1:745052584213:ios:b24f7e4b014da850fa111c',
    messagingSenderId: '745052584213',
    projectId: 'hungergo-4f4de',
    storageBucket: 'hungergo-4f4de.firebasestorage.app',
    iosBundleId: 'com.example.mind',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKHx1iv2FV7DxHbS7NwyVeQ-PfWjI16tM',
    appId: '1:745052584213:ios:b24f7e4b014da850fa111c',
    messagingSenderId: '745052584213',
    projectId: 'hungergo-4f4de',
    storageBucket: 'hungergo-4f4de.firebasestorage.app',
    iosBundleId: 'com.example.mind',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSE5yWof7P9p9r46dh3hMVj634cnRKthQ',
    appId: '1:745052584213:web:9173acdc574fab2afa111c',
    messagingSenderId: '745052584213',
    projectId: 'hungergo-4f4de',
    authDomain: 'hungergo-4f4de.firebaseapp.com',
    storageBucket: 'hungergo-4f4de.firebasestorage.app',
    measurementId: 'G-Y65078QHSS',
  );
}
